apiVersion: v1
kind: Pod
metadata:
  name: test-config-maps-from-file
  labels:
    name: test-config-maps-from-file
spec:
  containers:
  - name: test-config-maps-from-file
    image: busybox
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: meu-configmap-vol
        mountPath: /etc/fruts
        
  volumes:
    - name: meu-configmap-vol
      configMap:
        name: cores-frutas
         