apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: giropops-cron
spec:
 schedule: "*/1 * * * *"
 jobTemplate:
   spec:
     template:
       spec:
         containers:
           - name: giropops-cron
             image: busybox
             args:
              - /bin/sh
              - -c
              - date; echo Bem vindo ao descomplicando o Kubernetes -- LINUXTIPS; sleep 30
         restartPolicy: OnFailure