kind: Pod
apiVersion: v1
metadata:
  name: meu-pod2
spec:
  containers:
    - name: meu-container2
      image: busybox
      volumeMounts:
      - mountPath: "/data"
        name: meu-volume
  volumes:
    - name: meu-volume
      persistentVolumeClaim:
        claimName: csi-pvc-renato