apiVersion: v1
kind: PersistentVolume
metadata:
  name: primeiro-pv
spec:
 capacity:
   storage: 1Gi
 acessModes:
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
   path: /opt/dados
   server: 172.xx.xx.xxx
   readOnly: false
