apiVersion: v1
kind: Pod
metadata:
  name: busybox-test-secret
  labels:
    name: busybox
    app: busybox-test-secret
spec:
  containers:
  - name: busybox-test-secret
    image: busybox
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /tmp/giropops
        name: my-volume-secret
  volumes:
    - name: my-volume-secret
      secret:
        secretName: my-password