apiVersion: v1
kind: Pod
metadata:
  name: test-secret-env
  labels:
    name: test-secret-env
spec:
  containers:
  - name: test-secret-env
    image: busybox
    command:
      - sleep
      - "3600"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: my-literal-secret
            key: user
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-literal-secret
            key: password
      

